version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: timakaaliebe
      POSTGRES_PASSWORD: test
      POSTGRES_DB: aphos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timakaaliebe"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://timakaaliebe:test@db:5432/aphos?schema=public
      BOT_TOKEN: ${BOT_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_BOT_NAME: ${NEXT_PUBLIC_BOT_NAME}
      NEXT_PUBLIC_COMMUNITY_LINK: ${NEXT_PUBLIC_COMMUNITY_LINK}
      TELEGRAM_CHANNEL_USERNAME: ${TELEGRAM_CHANNEL_USERNAME}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      NODE_ENV: production
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
