import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.photo.createMany({
    data: [
      {
        defaultUrl: "/sofa4-default.png",
        nakedUrl: "/sofa4-naked.png",
        name: "Sofia",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/eva-default.png",
        nakedUrl: "/eva-naked.png",
        name: "Eva",
        price: 1500,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/masha-efron-default.png",
        nakedUrl: "/masha-efron-naked.png",
        name: "Masha",
        price: 2000,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/veronica-default.png",
        nakedUrl: "/veronica-naked.png",
        name: "Veronika",
        price: 1200,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/veselko-default.png",
        nakedUrl: "/veselko-naked.png",
        name: "Lera",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/sofia-default.png",
        nakedUrl: "/sofia-naked.png",
        name: "Sofia",
        price: 1000,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/ulya-default.png",
        nakedUrl: "/ulya-naked.png",
        name: "Ulya",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/rita-default.png",
        nakedUrl: "/rita-naked.png",
        name: "Rita",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/polyakova-default.png",
        nakedUrl: "/polyakova-naked.png",
        name: "Liza",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/nika-default.png",
        nakedUrl: "/nika-naked.png",
        name: "Nika",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/masha-ignatkina-default.png",
        nakedUrl: "/masha-ignatkina-naked.png",
        name: "Masha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/liza-default.png",
        nakedUrl: "/liza-naked.png",
        name: "Liza",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/kalin-default.png",
        nakedUrl: "/kalin-naked.png",
        name: "Nika",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/dasha-wels-default.png",
        nakedUrl: "/dasha-wels-naked.png",
        name: "Masha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/dasha-putesh-default.png",
        nakedUrl: "/dasha-putesh-naked.png",
        name: "Dasha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/bebe-default.png",
        nakedUrl: "/bebe-naked.png",
        name: "Liza",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/anya-default.png",
        nakedUrl: "/anya-naked.png",
        name: "Anya",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/alisa-default.png",
        nakedUrl: "/alisa-naked.png",
        name: "Alisa",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/veronica8-default.png",
        nakedUrl: "/veronica8-naked.png",
        name: "Veronika",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/sasha-sweet-default.png",
        nakedUrl: "/sasha-sweet-naked.png",
        name: "Sasha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/sasha-kras-default.png",
        nakedUrl: "/sasha-kras-naked.png",
        name: "Sasha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/sasha-default.png",
        nakedUrl: "/sasha-naked.png",
        name: "Sasha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/milana-default.png",
        nakedUrl: "/milana-naked.png",
        name: "Milana",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/masha-ogark-default.png",
        nakedUrl: "/masha-ogark-naked.png",
        name: "Masha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/lera2-default.png",
        nakedUrl: "/lera2-naked.png",
        name: "Lera",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/lera-porox-default.png",
        nakedUrl: "/lera-porox-naked.png",
        name: "Lera",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/ksusha-default.png",
        nakedUrl: "/ksusha-naked.png",
        name: "Ksusha",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/kamila-default.png",
        nakedUrl: "/kamila-naked.png",
        name: "Kamila",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/elis-default.png",
        nakedUrl: "/elis-naked.png",
        name: "Elis",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/arina-medved-default.png",
        nakedUrl: "/arina-medved-naked.png",
        name: "Arina",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/arina-default.png",
        nakedUrl: "/arina-naked.png",
        name: "Arina",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/anya-tg-default.png",
        nakedUrl: "/anya-tg-naked.png",
        name: "Anya",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
      {
        defaultUrl: "/angel-default.png",
        nakedUrl: "/angel-naked.png",
        name: "Stefania",
        price: 1800,
        rating: 0,
        ratingStore: [],
        reviews: 0,
      },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
