import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // await prisma.photo.createMany({
  //   data: [
  //     {
  //       defaultUrl: "/sofa4-default.png",
  //       nakedUrl: "/sofa4-naked.png",
  //       name: "Sofia",
  //       price: 600000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/eva-default.png",
  //       nakedUrl: "/eva-naked.png",
  //       name: "Eva",
  //       price: 700000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/masha-efron-default.png",
  //       nakedUrl: "/masha-efron-naked.png",
  //       name: "Masha",
  //       price: 700000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/veronica-default.png",
  //       nakedUrl: "/veronica-naked.png",
  //       name: "Veronika",
  //       price: 500000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/veselko-default.png",
  //       nakedUrl: "/veselko-naked.png",
  //       name: "Lera",
  //       price: 700000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/sofia-default.png",
  //       nakedUrl: "/sofia-naked.png",
  //       name: "Sofia",
  //       price: 750000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/ulya-default.png",
  //       nakedUrl: "/ulya-naked.png",
  //       name: "Ulya",
  //       price: 750000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/rita-default.png",
  //       nakedUrl: "/rita-naked.png",
  //       name: "Rita",
  //       price: 500000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/polyakova-default.png",
  //       nakedUrl: "/polyakova-naked.png",
  //       name: "Liza",
  //       price: 600000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/nika-default.png",
  //       nakedUrl: "/nika-naked.png",
  //       name: "Nika",
  //       price: 600000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/masha-ignatkina-default.png",
  //       nakedUrl: "/masha-ignatkina-naked.png",
  //       name: "Masha",
  //       price: 600000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/liza-default.png",
  //       nakedUrl: "/liza-naked.png",
  //       name: "Liza",
  //       price: 800000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/kalin-default.png",
  //       nakedUrl: "/kalin-naked.png",
  //       name: "Nika",
  //       price: 800000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/dasha-wels-default.png",
  //       nakedUrl: "/dasha-wels-naked.png",
  //       name: "Masha",
  //       price: 700000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/dasha-putesh-default.png",
  //       nakedUrl: "/dasha-putesh-naked.png",
  //       name: "Dasha",
  //       price: 500000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/bebe-default.png",
  //       nakedUrl: "/bebe-naked.png",
  //       name: "Liza",
  //       price: 800000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/anya-default.png",
  //       nakedUrl: "/anya-naked.png",
  //       name: "Anya",
  //       price: 800000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/alisa-default.png",
  //       nakedUrl: "/alisa-naked.png",
  //       name: "Alisa",
  //       price: 800000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/veronica8-default.png",
  //       nakedUrl: "/veronica8-naked.png",
  //       name: "Veronika",
  //       price: 700000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/sasha-sweet-default.png",
  //       nakedUrl: "/sasha-sweet-naked.png",
  //       name: "Sasha",
  //       price: 1000000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/sasha-kras-default.png",
  //       nakedUrl: "/sasha-kras-naked.png",
  //       name: "Sasha",
  //       price: 600000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/sasha-default.png",
  //       nakedUrl: "/sasha-naked.png",
  //       name: "Sasha",
  //       price: 700000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/milana-default.png",
  //       nakedUrl: "/milana-naked.png",
  //       name: "Milana",
  //       price: 1_500_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/masha-ogark-default.png",
  //       nakedUrl: "/masha-ogark-naked.png",
  //       name: "Masha",
  //       price: 800_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/lera2-default.png",
  //       nakedUrl: "/lera2-naked.png",
  //       name: "Lera",
  //       price: 700_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/lera-porox-default.png",
  //       nakedUrl: "/lera-porox-naked.png",
  //       name: "Lera",
  //       price: 650_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/ksusha-default.png",
  //       nakedUrl: "/ksusha-naked.png",
  //       name: "Ksusha",
  //       price: 900_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/kamila-default.png",
  //       nakedUrl: "/kamila-naked.png",
  //       name: "Kamila",
  //       price: 800_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/elis-default.png",
  //       nakedUrl: "/elis-naked.png",
  //       name: "Elis",
  //       price: 650_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/arina-medved-default.png",
  //       nakedUrl: "/arina-medved-naked.png",
  //       name: "Arina",
  //       price: 1_500_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/arina-default.png",
  //       nakedUrl: "/arina-naked.png",
  //       name: "Arina",
  //       price: 750_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/anya-tg-default.png",
  //       nakedUrl: "/anya-tg-naked.png",
  //       name: "Anya",
  //       price: 750_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/angel-default.png",
  //       nakedUrl: "/angel-naked.png",
  //       name: "Stefania",
  //       price: 700_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/varvara-default.png",
  //       nakedUrl: "/varvara-naked.png",
  //       name: "Varvara",
  //       price: 800_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/liza-haris-default.png",
  //       nakedUrl: "/liza-haris-naked.png",
  //       name: "Liza",
  //       price: 500_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/milena-default.png",
  //       nakedUrl: "/milena-naked.png",
  //       name: "Milena",
  //       price: 650_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/sofia-ger-default.png",
  //       nakedUrl: "/sofia-ger-naked.png",
  //       name: "Sofia",
  //       price: 700_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/ksusha-laz-default.png",
  //       nakedUrl: "/ksusha-laz-naked.png",
  //       name: "Ksusha",
  //       price: 650_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/nastya-fom-default.png",
  //       nakedUrl: "/nastya-fom-naked.png",
  //       name: "Nastya",
  //       price: 700_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/dasha-step-default.png",
  //       nakedUrl: "/dasha-step-naked.png",
  //       name: "Dasha",
  //       price: 700_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/dasha-bogd-default.png",
  //       nakedUrl: "/dasha-bogd-naked.png",
  //       name: "Dasha",
  //       price: 800_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/katya-default.png",
  //       nakedUrl: "/katya-naked.png",
  //       name: "Katya",
  //       price: 800_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/dasha-kunic-default.png",
  //       nakedUrl: "/dasha-kunic-naked.png",
  //       name: "Dasha",
  //       price: 750_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/arina-chern-default.png",
  //       nakedUrl: "/arina-chern-naked.png",
  //       name: "Arina",
  //       price: 750_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //     {
  //       defaultUrl: "/masha-osk-default.png",
  //       nakedUrl: "/masha-osk-naked.png",
  //       name: "Masha",
  //       price: 650_000,
  //       rating: 0,
  //       ratingStore: [],
  //       reviews: 0,
  //     },
  //   ],
  // });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
